services:
  forguarder:
    build:
      context: forguarder
    container_name: forguarder
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Beware this essentially provides root access to the system
