name: Compose build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show docker compose version
        uses: docker compose version

      - name: Check compose format
        uses: docker compose config

      - name: Build compose
        uses: docker compose build
