name: ForGuarder test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FORGUARD_API_PORT: 3030

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            forguarder

      - name: Move forguarder files to root
        run: mv forguarder/* . && rm -rf forguarder

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Start API server (background)
        run: npm run start --workspace api &
        env:
          FORGUARD_API_PORT: ${{ env.FORGUARD_API_PORT }}

      - name: Wait for the server to be UP
        run: npx --yes wait-on http://localhost:${{ env.FORGUARD_API_PORT }} --timeout 1m

      - name: Check the server is responding to requests
        run: curl --fail http://localhost:${{ env.FORGUARD_API_PORT }}/healthcheck || (echo "Server did not respond to the test request" && exit 1)